name: Release

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Flutter
        uses: bancolombia/flutter-setup-action@v1
        with:
          #channel: 'stable'
          #flutter-version: '3.32.0'
          #java-version: '17'
          cache: 'true'

      - name: Install gradle
        run: |
          sudo apt update
          sudo apt install gradle

      - name: gradlew
        run: |
          cd android
          gradle wrapper
          chmod +x gradlew
          cd ..

      - name: build
        run: ./build.sh -k -a
